[install_path] #mountpoint
root_path = '/mnt'    #path to mounted root filesystem for install
efi_path = '/mnt/efi'

[reflector]
countries = ['TH', 'SG']

[settings]
hostname = 'arch'
username = 'gttwt'
root_login = false # "false" mean wont ask for root password

[settings.locale]
locale_gen = "en_SG.UTF-8 UTF-8"
locale_conf = "LANG=en_SG.UTF-8"
vconsole_conf = "KEYMAP=us"
localtime = 'Asia/Bangkok'

[package]
base = ['base', 'linux-lts', 'linux-lts-headers', 'linux-firmware']
base_ucode = ['amd_ucode']
network = [
	'iptables-nft'
	'networkmanager',
	'network-manager-applet',
	'iwd',
	'wireless_tools',
	'smartmontools',
	'wpa_supplicant',
	'firewalld',
	'inetutils',
]
audio = [
	'sof-firmware',
	'alsa-utils',
	'pipewire',
	'pipewire-alsa',
	'pipewire-pulse',
	'pipewire-jack',
	'gst-plugin-pipewire',
	'libpulse wireplumber',
]
desktop = [
	'noto-fonts'
	'plasma-meta',
	'konsole',
	'kate',
	'dolphin',
	'ark',
	'plasma-workspace',
	'xdg-utils',
]
nvidia_open = [
	'xorg-server',
	'xorg-xinit',
	'nvidia-open-dkms',
	'dkms',
	'libva-nvidia-driver',
]
utils = ['rsync', 'reflector']
additional = ['neovim', 'firefox', 'zsh', 'grml-zsh-config']


[boot_config]
mkinitcpio_conf = '''
MODULES=()
BINARIES=()
FILES=()
HOOKS=(base systemd autodetect microcode modconf kms keyboard keymap sd-vconsole sd-encrypt block filesystems fsck)'''
linux-lts_preset = '''
# mkinitcpio preset file for the 'linux-lts' package

#ALL_config="/etc/mkinitcpio.conf"
ALL_kver="/boot/vmlinuz-linux-lts"
#ALL_kerneldest="/boot/vmlinuz-linux-lts"

PRESETS=('default')
#PRESETS=('default' 'fallback')

#default_config="/etc/mkinitcpio.conf"
default_image="/boot/initramfs-linux-lts.img"
default_uki="/efi/EFI/Linux/arch-linux-lts.efi"
#default_options="--splash /usr/share/systemd/bootctl/splash-arch.bmp"

#fallback_config="/etc/mkinitcpio.conf"
#fallback_image="/boot/initramfs-linux-lts-fallback.img"
#fallback_uki="/efi/EFI/Linux/arch-linux-lts-fallback.efi"
#fallback_options="-S autodetect"
'''
